name: CrackMapExec Tests & Build

on: [push]

jobs:
  build:
    name: CrackMapExec Tests on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      max-parallel: 4
      matrix:
        os: [ubuntu-latest, macOS-latest, windows-latest]

    steps:
    - uses: actions/checkout@v2
      with:
        submodules: 'recursive'
    - name: CrackMapExec tests on ${{ matrix.os }}
      uses: actions/setup-python@v1
      with:
        python-version: 3.8
    - name: Build binaries with Shiv
      run: |
        pip install shiv
        python build_collector.py
    - name: Upload cme binary
      uses: actions/upload-artifact@master
      with:
        name: cme-${{ matrix.os }}
        path: bin/cme
    - name: Upload cmedb binary
      uses: actions/upload-artifact@master
      with:
        name: cmedb-${{ matrix.os }}
        path: bin/cmedb
